// POSTS
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const GET_POSTS_DATA = 'GET_POSTS_DATA';
export const GET_CATEGORY_POSTS_DATA = 'GET_CATEGORY_POSTS_DATA';
export const CREATE_NEW_POST = 'CREATE_NEW_POST';
export const UPDATE_POST_SCORE = 'UPDATE_POST_SCORE';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';

// CATEGORY
export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA';

// COMMENTS
export const GET_COMMENTS = 'GET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT_SCORE = 'UPDATE_COMMENT_SCORE';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
